#Range: 0.0 ~ 3.4028234663852886E38
"Iron Bow damage bonus" = 1.2
#Range: 0.0 ~ 3.4028234663852886E38
"Golden Bow damage bonus" = 1.4
#Range: 0.0 ~ 3.4028234663852886E38
"Diamond Bow damage bonus" = 1.6
#Range: 0.0 ~ 3.4028234663852886E38
"Emerald Bow damage bonus" = 1.8
#Range: 0.0 ~ 3.4028234663852886E38
"Netherite Bow damage bonus" = 2.0
#Range: 0.0 ~ 3.4028234663852886E38
"Iron Crossbow damage bonus" = 1.2
#Range: 0.0 ~ 3.4028234663852886E38
"Golden Crossbow damage bonus" = 1.4
#Range: 0.0 ~ 3.4028234663852886E38
"Diamond Crossbow damage bonus" = 1.6
#Range: 0.0 ~ 3.4028234663852886E38
"Emerald Crossbow damage bonus" = 1.8
#Range: 0.0 ~ 3.4028234663852886E38
"Netherite Crossbow damage bonus" = 2.0

