name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97849f7a43f5a152b300427e6ec58bea6f9fa7a655146a467609b1febea1e33e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
