name = "Crafters Modpack"
author = "Alessy - Bksp"
version = "1.0.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a85ce187aeba38d6703b8a3d3fbc913bb87d7384b7533b3c30f1abde5ee3bebd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
