name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7cf6f45a47e72539f86a10c42566e4c99cb9e30098132cc43c86f99a26792cf"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
