name = "Crafters Modpack"
author = "Alessy - Bksp"
 $m = $args[0]; $v = [int]$m.Groups[2].Value + 1; 'version = "' + $m.Groups[1].Value + $v + '"' 
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d792b5dca6ecc43cf9b920d80a746970d7a01deb13d1da47b9c1df82c3529cb6"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
