name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2668d7046bd57d33e8a74e404cfa67893a98617f4f58c66d938a336d36054c32"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
