name = "Crafters Modpack"
author = "Logan"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b52b3ffe492cc2987040891fbb7b0362492d52e25ac0182257230c654caaba7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
