name = "Crafters Modpack"
author = "Bksp"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4e45cd5c793baeaac0530bc3820b6cdff709c140092654f065a32b0d0ace733"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
