# Don't change this! Version used to track needed updates.
version = 0
enable = true
enableDebugWindow = false
enableWindow = true
disableNames = [
    "None"
]
windowMoveDuration = 6.0
windowMoveEase = "OUT_BACK"
windowMoveX = 0.0
windowMoveY = 50.0
windowGradientDuration = 8.0
windowGradientEase = "IN_OUT_SINE"
enableHover = true
hoverDuration = 4.0
hoverEase = "IN_OUT_SINE"
hoverScale = 1.2
enableTooltip = true
tooltipDuration = 6.0
tooltipEase = "OUT_CIRC"
enableClickItem = true
clickItemDuration = 5.0
enableOutput = true
outputDuration = 5.0
outputEase = "OUT_BACK"
enableHoldItem = false
holdZoomInDuration = 8.0
holdZoomInEase = "OUT_QUINT"
holdZoomScale = 1.4
holdZoomOutDuration = 2.0
holdZoomOutEase = "OUT_QUART"
enableLack = false
lackDuration = 8.0
lackShakeStrength = 0.0
enableExp = true
expDuration = 4.0
expEase = "OUT_BACK"
expScale = 4.0
enableChat = true
chatOpenMoveDuration = 4.0
chatOpenMoveEase = "IN_OUT_SINE"
chatOpenMoveX = 0.0
chatOpenMoveY = 50.0
chatOpenGradientDuration = 6.0
chatOpenGradientEase = "IN_OUT_SINE"
enableChatComp = true
chatCompMoveDuration = 4.0
chatCompMoveEase = "IN_OUT_SINE"
chatCompMoveX = -500.0
chatCompMoveY = 0.0
chatCompGradientDuration = 6.0
chatCompGradientEase = "IN_OUT_SINE"